steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/github-webhook-service:latest"
      - "-f"
      - "run/Dockerfile"
      - "."
    id: "build-image"

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/github-webhook-service:latest"
    id: "push-image"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/github-webhook-service:latest"
      - "--region"
      - "${_LOCATION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--set-env-vars"
      - "NODE_ENV=production"
      - "--update-secrets"
      - "GITHUB_TOKEN=github-token:latest"
      - "--update-secrets"
      - "GITHUB_WEBHOOK_SECRET=github-webhook-secret:latest"
      - "--set-env-vars"
      - "GITHUB_WEBHOOK_BASEURL=${_WEBHOOK_BASE_URL}"
    id: "deploy-service"

images:
  - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/github-webhook-service:latest"

# Substitution variables
substitutions:
  _LOCATION: "us-central1"
  _REPOSITORY: "github-webhook-service"
  _SERVICE_NAME: "github-webhook-service"
  _WEBHOOK_BASE_URL: "https://github-webhook-service-REPLACE_WITH_HASH-uc.a.run.app"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

timeout: "1200s"
